name: Lint
on:
  pull_request:
    paths:
      - 'index.js'
      - .github/workflows/lint.yml

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm ci
        run: npm ci
      - name: ESLint
        run: npm run lint
